// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/20/2024, 11:38:42 AM
const configMerger = require("/Users/mohammedhussin/Desktop/Projects/Fe/Aleen.website/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{"colors":{"main":"#00BC71","golden":"#D7AF5C","secondary":"#FFB443"}},"container":{"center":true,"padding":"1rem"}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/mohammedhussin/Desktop/Projects/Fe/Aleen.website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohammedhussin/Desktop/Projects/Fe/Aleen.website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohammedhussin/Desktop/Projects/Fe/Aleen.website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohammedhussin/Desktop/Projects/Fe/Aleen.website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohammedhussin/Desktop/Projects/Fe/Aleen.website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mohammedhussin/Desktop/Projects/Fe/Aleen.website/plugins/**/*.{js,ts,mjs}","/Users/mohammedhussin/Desktop/Projects/Fe/Aleen.website/composables/**/*.{js,ts,mjs}","/Users/mohammedhussin/Desktop/Projects/Fe/Aleen.website/utils/**/*.{js,ts,mjs}","/Users/mohammedhussin/Desktop/Projects/Fe/Aleen.website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mohammedhussin/Desktop/Projects/Fe/Aleen.website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mohammedhussin/Desktop/Projects/Fe/Aleen.website/app.config.{js,ts,mjs}"] }));

module.exports = config
